# Base image with CUDA support for GPU acceleration
FROM nvidia/cuda:12.1.1-base-ubuntu22.04

LABEL maintainer="NASA IMPACT"

# Set non-interactive mode for apt-get
ARG DEBIAN_FRONTEND=noninteractive

# Install necessary packages
RUN apt-get update && \
    apt-get install -y software-properties-common python3.11-dev python3-pip \
    nginx git libgdal-dev --fix-missing && \
    rm -rf /var/lib/apt/lists/*

# Create a non-root user and switch to it
RUN useradd -m myuser

# Switch to the non-root user
USER myuser

# Install virtualenv and create a virtual environment in /opt/venv
RUN python3 -m venv /opt/venv

# Set environment variables for the virtual environment
ENV VIRTUAL_ENV=/opt/venv
ENV PATH="$VIRTUAL_ENV/bin:$PATH"

# Upgrade pip within the virtual environment
RUN pip install --upgrade pip

# Install Python dependencies within the virtual environment
COPY requirements.txt requirements.txt
RUN pip install -r requirements.txt

# Set environment variables for CUDA support
ENV CUDA_VISIBLE_DEVICES=0,1,2
ENV CUDA_HOME=/usr/local/cuda

# Create directory for model storage
RUN mkdir /models

# Set working directory and copy the code to the container
COPY code /opt/program

# Set environment variables to ensure Python outputs logs properly
ENV PYTHONUNBUFFERED=TRUE
ENV PYTHONDONTWRITEBYTECODE=TRUE
ENV PATH="/opt/program:${PATH}"

# Set the working directory for the code
WORKDIR /opt/program

# Expose port for the app (useful when running with FastAPI)
EXPOSE 8080

# Command to run the application using Uvicorn
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8080"]
