worker_processes 1;
daemon off;  # Prevent forking

pid /tmp/nginx.pid;
error_log /dev/stderr;
access_log /dev/stdout combined;

events {
  # defaults
}

http {
  include /etc/nginx/mime.types;
  default_type application/octet-stream;

  upstream gunicorn {
    server 127.0.0.1:8000;  # Use TCP socket
  }

  server {
    listen 8080 deferred;  # Default GCP port
    client_max_body_size 5m;

    keepalive_timeout 5;
    proxy_read_timeout 1200s;

    location ~ ^/(ping|invocations) {
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_set_header Host $http_host;
      proxy_redirect off;
      proxy_pass http://gunicorn;
    }

    location / {
      return 404 '{"error": "Endpoint not found"}';
    }
  }
}
